### ISSUE TITLE
Remove 'watch' config in pm2 config.json

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#10]
Each app (UI or API) has a `ecosystem.config.json` that configures how [pm2](https://pm2.keymetrics.io/) runs.

For some reason, some configure pm2 to watch for changes (which means pm2 will automatically restart when a file is changed) but others don't.

~We can't think of a situation when developing when we wouldn't want this to happen so we should be going through each and enabling this option.~

**Update!!**

We've been working on the service for a while now and we _never_ use watch with pm2. Because working with the Vagrant box is the norm for us it makes file watching 'problematic'. If we do want to quickly restart after changes we prefer to use nodemon.

We even just [Added an alias for Nodemon file watchers error](https://gitlab-dev.aws-int.defra.cloud/water-abstraction/wal-vagrant/-/merge_requests/27), caused by too many file watches being registered. So, it is in our interest to remove the pm2 watch config to help avoid this error with Nodemon.

This is why I've updated this task from making them consistent to just removing all watch config from pm2.

- [x] water-abstraction-import
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-returns
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-ui

**Comment by Beckyrose200** [comment]
<img src="https://media3.giphy.com/media/lD76yTC5zxZPG/giphy.gif"/>
