### ISSUE TITLE
Refactoring the alternate 2PT engine

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#105]
> This is not an issue!

We just need a place to manage a TODO list of things we need to change 'properly' when it comes to refactoring <https://github.com/DEFRA/water-abstraction-system/pull/458> into something ready for production.

- [x] Hook up a new match & allocate service to `StartBillRunProcessService`
- [x] Create a way to test the output of `MatchAndAllocateService`
- [x] Break out fetching the charge versions into a service with unit tests (includes raising a PR)
- [x] Break out fetching the returns into a service with unit tests (includes raising a PR)
- [x] Move `DetermineChargePeriodService` up a level from `/bill-runs/supplementary`
- [x] Complete `DetermineAbstractionPeriodsService` (we extracted how to determine abstractions periods out of `CalculateAuthorisedAndBillableDaysService` into a service. It just needs a once-over and pertinent comments copied over. Then it needs to be moved to `/services/bill-runs` and `CalculateAuthorisedAndBillableDaysService` refactored to use it)
- [x] Documentation and Unit tests for new `FetchLicencesService`
- [x] Documentation and Unit tests for new `FetchReturnsForLicenceService`
- [x] Documentation and Unit tests for new `PrepareLicencesForAllocationService`
- [x] Documentation and Unit tests for new `MatchReturnsToChargeElementService`
- [ ] Documentation and Unit tests for new `AllocateReturnsToLicenceService`
- [x] Documentation and Unit tests for new `PersistAllocatedLicencesToResultsService`
- [x] Create models, helpers and then unit tests for new result tables
- [x] Add unit tests and comments for new `periodsOverlap()` helper

**Comment by Jozzey** [comment]
`DetermineChargePeriodService` moved in https://github.com/DEFRA/water-abstraction-system/pull/528

**Comment by Jozzey** [comment]
`DetermineAbstractionPeriodsService` created in this PR https://github.com/DEFRA/water-abstraction-system/pull/529

**Comment by Beckyrose200** [comment]
`FetchChargeVersionsService` created in this PR https://github.com/DEFRA/water-abstraction-system/pull/546

**Comment by Beckyrose200** [comment]
`periodsOverlap` created in this PR https://github.com/DEFRA/water-abstraction-system/pull/548

**Comment by Beckyrose200** [comment]
Migrations, models, helpers and unit tests for the 3 new tables https://github.com/DEFRA/water-abstraction-system/pull/552

**Comment by Cruikshanks** [comment]
Cor blimey! This issue is still around. 😁 

We are so many steps on from the refactoring of our ad-hoc engine branch that this is completely redundant.
