### ISSUE TITLE
Inconsistent use of nodemon

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#11]
Following on from issue #10 some projects also have [nodemon](https://www.npmjs.com/package/nodemon) as a dependency.

If we're sticking with the previous team's convention of using pm2 to do the same thing we should go through and drop it. One less dependency to maintain!

**Comment by jonathangoulding** [comment]
This is my fault. I will go back through and remove.

**Comment by jonathangoulding** [comment]
Addressed in:

UI - https://github.com/DEFRA/water-abstraction-ui/pull/2105
CRM - https://github.com/DEFRA/water-abstraction-service/pull/1691
SERVICE - https://github.com/DEFRA/water-abstraction-tactical-crm/pull/886

**Comment by jonathangoulding** [comment]
Cheers, @Cruikshanks 

Closed as all branches merges.
