### ISSUE TITLE
Correct how the `handler` has been added to some of the routes so they all follow the same pattern

### ISSUE THREAD

**Issue by Jozzey** [DEFRA/water-abstraction-team#122]
It has been noticed that in some of our routes the `handler` is within the `options` property
```javascript
{
  method: 'POST',
  path: '/bills/{id}/remove',
  options: {
    handler: BillsController.submitRemove,
    auth: {
      access: {
        scope: ['billing']
      }
    }
  }
}
``` 
Whilst in others it is outside
```javascript
{
  method: 'GET',
  path: '/bill-runs',
  handler: BillRunsController.index,
  options: {
    auth: {
      access: {
        scope: ['billing']
      }
    }
  }
}
``` 
This is down to some contradiction in the Hapi documentation. The [Hapi tutorial for routing](https://hapi.dev/tutorials/routing/?lang=en_US) gives an example in the "Options" section of the `handler` being outside of the `options` property. Whereas the [API documentation](https://hapi.dev/api/?v=21.3.3#-routeoptionshandler) has the `handler` within the `options` property.

We have taken the decision that the API docs trump the tutorial. So for all of our routes, we need to make sure that the `handler` is within the `options` property. This is only applicable to the [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) repo.

**Comment by rvsiyad** [comment]
<img src="https://media2.giphy.com/media/ENagATV1Gr9eg/giphy.gif"/>
