### ISSUE TITLE
Delete - water-abstraction-acceptance-tests reos

### ISSUE THREAD

**Issue by jonathangoulding** [DEFRA/water-abstraction-team#15]
https://github.com/DEFRA/water-abstraction-acceptance-tests

Is "dead as a door nail"

We double check and delete it

**Comment by Cruikshanks** [comment]
I'll check in with QA folk and confirm. But yep,  💯  agree this can go.

**Comment by Cruikshanks** [comment]
So, the QA folks have come back and confirmed that the repo is defunct. However, they want the chance to check the scenarios it contains and see if any need migrating over to our current acceptance tests (these are now part of the UI repo).

I've marked the repo as `archived` to make it clear it is no longer used (after I'd cleaned up the branches and settings).

I'm happy to mark this one as done if you are @jonathangoulding .

**Comment by Cruikshanks** [comment]
Marking this one as done for now
