### ISSUE TITLE
Delete - water repo

### ISSUE THREAD

**Issue by jonathangoulding** [DEFRA/water-abstraction-team#17]
https://github.com/DEFRA/water

looks like a prototype that has not been touched for 3 years

**Comment by Cruikshanks** [comment]
This one might have been a prototype that started morphing into the alpha version of the service (a common practice 5 years ago).

I'm guessing someone then saw a talk on micro-services and the rest as they say is history!

Just double-checking with our designer though that this can go (assuming he knows anything about it 🤷 ).

**Comment by Cruikshanks** [comment]
Confirmed with UCD it's not something they are aware. They have taken a copy but agreed it can go.

I've archived it off to our GitLab repo and now deleted from GitHub.
