### ISSUE TITLE
Remove unneeded packages

### ISSUE THREAD

**Issue by StuAA78** [DEFRA/water-abstraction-team#26]
We have some dependencies which aren't needed at all -- for example, they may be things that were originally in use but were since dropped, and have never been removed from `package.json`. This is slightly different to the issue of [packages which are in use but are deprecated](https://github.com/DEFRA/water-abstraction-team/issues/22) so keep the two separate.

A quick check of the UI as an example results in the following:
```
❯ npx depcheck   
Unused dependencies
* accessible-autocomplete
* acorn
* debug
* deep-extend
* deep-map
* glob
* hapi-auth-jwt2
* http-errors
* iframe-resizer
* minimatch
* moment-timezone
* path
* pg
* pg-boss
* randomatic
* slugify
* winston
Unused devDependencies
* @babel/cli
* @babel/register
* chai
* chromedriver
* cypress-multi-reporters
* mocha
* mochawesome
```

This check isn't perfect (for example, `mochawesome` is set as a reporter in `cypress.json`) but it at least gives us a start at identifying dependencies we don't need.

- [x] water-abstraction-admin-ui
- [x] water-abstraction-import
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-returns
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-ui

**Comment by Cruikshanks** [comment]
I did not know we could do this!

![drooling](https://user-images.githubusercontent.com/1789650/168771940-c359cf40-7e53-44e6-9244-6ea8bb80ee08.gif)

Just do it (probably best one at a time 😁 ) and see what breaks!

**Comment by Jozzey** [comment]
<img src="https://media4.giphy.com/media/fOzVB89gnznJXaZ1Ti/giphy.gif"/>
