### ISSUE TITLE
Rename test files from `filename.js` to `filename.test.js`

### ISSUE THREAD

**Issue by StuAA78** [DEFRA/water-abstraction-team#27]
VS Code puts a nice distinctive icon next to test files which are named in the format `filename.test.js`. This makes it easy to identify which files can be ignored when searching through the code for things:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/43574728/168584021-b5b8f512-b5a7-46b9-9735-d80d3a7c767f.png">

Unfortunately, our test files are named simply `filename.js`, so we don't get this icon when we search and can't easily identify the test files we can ignore:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/43574728/168584245-e87c8362-dbf2-4d15-94e7-9d85fd480ef6.png">

 We should therefore consider renaming all the test files in the format `filename.test.js`.

- [x] water-abstraction-ui
- [x] water-abstraction-admin-ui
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-import
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-returns
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-helpers
- [x] hapi-pg-rest-api

**Comment by StuAA78** [comment]
A quick way of doing this is to use ZSH's `zmv` command.

Drop into the test file folder and enter the following:

```bash
zmv -w -n '**/*.js' '$1$2.test.js' 
```

(If the command isn't found then `autoload zmv` first)

The `-w` flag enables implicit wildcards, so that `$1` matches the first wildcard in the source pattern (ie. the path as specified by `**/`) and `$2` matches the second wildcard (ie. the filename as specified by the single `*`).

The `-n` flag will output a preview of the files it's going to rename. If all looks satisfactory, run the command without it:

```bash
zmv -w '**/*.js' '$1$2.test.js' 
```

You'll most likely find some files are referred to by other tests (eg. test helpers) and can no longer be found after renaming, so you'll need to run the tests to identify them and rename them back. This is still likely to be quicker than renaming each file individually! :grin:

**Comment by Jozzey** [comment]
<img src="https://media4.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif"/>
