### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#3]
Most Water repos have hundreds of undeleted branches. They might be dead but having them around

- increases the size of the .git data
- just looks plain messy!

We just need to go through each repo and delete anything that is no longer active. It has been suggested we keep the last 5 release branches around 'just in case'. We should review this depending on our comfort levels and any changes made to the release process in the time between now and completing this task.

> Good one for anyone stuck in a meeting they can't contribute too!

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/hapi-pg-rest-api/branches/all

**Comment by jonathangoulding** [comment]
Removing any releases older than 5 releases

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-admin-ui/branches/all

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-helpers/branches/all

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-import/branches/all

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-permit-repository/branches/all

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-reporting/branches/all

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-returns/branches/all

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-tactical-idm/branches/all

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-tactical-crm/branches/all

**Comment by jonathangoulding** [comment]
Cleaned: https://github.com/DEFRA/water-abstraction-ui/branches/all

**Comment by jonathangoulding** [comment]
@Cruikshanks @StuAA78 @Stephan-Hough @Jozzey 

Can someone confirm these are all okay an close the issue.
