### ISSUE TITLE
HAPI-PG preSelect could abort/return results immediately

### ISSUE THREAD

**Issue by james-siteclick** [DEFRA/water-abstraction-team#32]
https://github.com/DEFRA/hapi-pg-rest-api

Could be useful to immediately return data from preSelect hook

**Comment by Cruikshanks** [comment]
The current dev team, having lived with the legacy code for more than a year and its use of [hapi-pg-rest-api](https://github.com/DEFRA/hapi-pg-rest-api) do not believe this would be useful. In fact, we are working to wipe the existence of this package from the face of the earth.

Therefore we won't be resolving this issue. 😬
