### ISSUE TITLE
HAPI-PG Delete many is not documented

### ISSUE THREAD

**Issue by james-siteclick** [DEFRA/water-abstraction-team#33]
<https://github.com/DEFRA/hapi-pg-rest-api>

Server and client support delete many rows with a filter:
```
await client.delete({ foo : 'bar'})
```
However this is not documented

**Comment by Cruikshanks** [comment]
The current dev team, having lived with the legacy code for more than a year and its use of [hapi-pg-rest-api](https://github.com/DEFRA/hapi-pg-rest-api) believes it is in the interest of everyone that this remains undocumented. In fact, we are working to wipe the existence of this package from the face of the earth.

Therefore we won't be resolving this issue.
