### ISSUE TITLE
HAPI-PG hapi 17 version does not support all features of 2.0 branch

### ISSUE THREAD

**Issue by james-siteclick** [DEFRA/water-abstraction-team#34]
<https://github.com/DEFRA/hapi-pg-rest-api>

e.g. delete multi

**Comment by Cruikshanks** [comment]
The current dev team, having lived with the legacy code for more than a year and its use of [hapi-pg-rest-api](https://github.com/DEFRA/hapi-pg-rest-api) still doesn't know what this means. In fact, we are working to wipe the existence of this package from the face of the earth.

Therefore we won't be resolving this issue. 😬
