### ISSUE TITLE
Remove docker files from repos (for now!)

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#38]
All our apps have a `Dockerfile` and `.dockerignore`. We even had some initial attempts at orchestration hidden away in GitLab and a fantastic effort was made with [water-abstraction-orchestration](https://github.com/DEFRA/water-abstraction-orchestration).

But the files are very basic and appear to be slightly modified `Hello, world` versions rather than properly tailored multi-stage builds. Added to that the apps themselves are no-way ready for Docker.

- Logging including output needs to be sorted
- Config, some of it hard-coded, and use of environment variables
- Use of cron for scheduled jobs

These are just some examples of things that will need sorting before they are. So, to avoid any further confusion and keep things clean, we need to run through the repos and remove any references to Docker; this includes files, config and documentation 😢 

One day though, one day we'll get them there! 🤞 🙏 

- [x] water-abstraction-ui
- [x] water-abstraction-admin-ui
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-import
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-returns
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting

**Comment by Beckyrose200** [comment]
![All Done LOTR](https://user-images.githubusercontent.com/91424856/192995023-2d7ccd43-14d0-4a7f-808c-04ddefca1d5e.gif)

**Comment by Beckyrose200** [comment]
All repos have had the docker files deleted as per the issue
