### ISSUE TITLE
Make GitHub CI workflow consistent

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#4]
We need to go through _all_ the Water repos (packages as well as apps) and ensure they are taking a common approach to how their GitHub CI workflow is implemented.

Along the way we should agree

- test all vs fail first approach (i.e. all stages in the pipeline are tested vs stop all further stages when one stage fails)
- inclusion of npm audit stage (we have snyk and GitHub plus to be a bit :trollface: npm audit _always_ seems to fail unless you are running a small `Hello, World!` app)

- [x] water-abstraction-ui
- [x] water-abstraction-admin-ui
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-import
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-returns
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-helpers
- [x] hapi-pg-rest-api

**Comment by jonathangoulding** [comment]
## Taken from a closed issue to address npm audit. 


If we rely on snyk & Dependabot for dependency management we can remove the audit job from the pipeline.

To remove:
Delete the Audit block here: https://github.com/DEFRA/water-abstraction-orchestration/blob/develop/.github/workflows/base-node-pipeline.yml#L15

All pipelines extend the base pipeline and will have an immediate effect.

If you want to "do it properly" then all repos have a line similar to this:
DEFRA/water-abstraction-orchestration/.github/workflows/base-node-pipeline.yml@develop

Replace the @develop with the new orchestration branch to test, merge the new pipeline on orchestration and revert the feature branch to develop (or just delete the PR/ branch)
