### ISSUE TITLE
Stop passing err to logger.error()

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#45]
All the apps use [Winston](https://github.com/winstonjs/winston) for logging. This is all set up in [water-abstraction-helpers](https://github.com/DEFRA/water-abstraction-helpers). The apps will create the logger instance via the helpers project, and it in turn uses Winston for the logging.

What we have found is if you have an error and call `logger.error(err)` we get an explosion of output in the logs. Quite literally _hundreds_ of lines of what just appears to be code, and mostly from a package we are using. Only rarely does it seem to be our code!

This often makes the logs unusable just at the point we really need them; when an error gets thrown. What we have found is if you pass `logger.error(err.stack)` you get something usable, but that doesn't pollute the logs with hundreds of lines of noise.

So, as an incremental step to make the logs usable until such time as we can re-write all logging, this covers a **Find & Replace** exercise to update any calls to `logger.error()` that just passes in the error instance.

- [x] water-abstraction-import
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-returns
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-ui

**Comment by Beckyrose200** [comment]
<img src="https://media1.giphy.com/media/nTqBNQXlEixLa/giphy.gif"/>
