### ISSUE TITLE
Move service status page from UI to system

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#54]
The current WABS UI features a `/service-status` page

<img width="1219" alt="Screenshot 2022-10-10 at 10 16 04" src="https://user-images.githubusercontent.com/1789650/194834132-3ba8dbe2-1b5f-4da1-8b87-d282e1c8b52a.png">

This is the ideal first 'UI' function to assimilate into [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system).

It's not a user feature, so no one will shout if we break it! There is no authentication, we don't have to worry about that topic yet. But it does involve

- bringing in the GOV.UK design elements
- figuring out what our asset pipeline should be
- deciding how we'll build our first page; where the view sits in the project etc

Once we have those figured out, the current service page does checks that involve

- talking to the DB
- talking to the other WABS services
- talking to the addressbase facade
- talking to the ClamAV

By performing the same checks we'll have figured out how **system** will integrate with the current service whilst things slowly get assimilated.

> IMPORTANT! This is a great 'figuring things out' function. In the same vein we are not limited to, or required to replicate everything the current `/service-status` page does. If there is an opportunity to improve what it does, or new things we can implement it is within the scope of this ticket.

**Comment by Jozzey** [comment]
This issue has now been resolved. The new status page can either be accessed locally from the `system` service using http://localhost:8013/health/info or by using the existing `/service-status` from the UI which will now redirect to our new page.
