### ISSUE TITLE
Remove verbose  from db migrate commands

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#65]
We needed to add a large data migration to fix an issue in [](). The fix worked but it broke CI. GitHub actions started erroring when the migrations ran with `##[error]stderr maxBuffer length exceeded`.

Unlike locally, where only the latest migrations are run, in CI all migrations are run all the time and our 2.5k SQL script (😳 😁 ) was obviously the straw that broke the camel's back.

We realised that so much was outputting because all our migration scripts have the `--verbose` flag set. When we removed it in this case, the problem was solved.

We don't need to see it, and it might avoid the same problem from happening to other repos. So, this issue is about going through the repos and removing `--verbose` from any migrate commands.

- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-permit-repository
- [x] water-abstraction-returns
- [x] water-abstraction-import
- [x] hapi-pg-rest-api

**Comment by Jozzey** [comment]
<img src="https://media3.giphy.com/media/3o6ZsZbUukGiYMf2a4/giphy.gif"/>
