### ISSUE TITLE
Start doing the minimum in /status checks

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#67]
AWS ELB's require an endpoint they can hit to confirm whether an app is running. They are commonly referred to as [health checks](https://aws.amazon.com/builders-library/implementing-health-checks/) and are used to determine whether the ELB should route traffic through to an app instance. In our apps, it is the `/status` endpoint.

The endpoint in all our repos reads in the `package.json` file to get the app's version number. This information is then used to support the `/service-status` page in the [water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui). Some of repos also include a test query to the DB to confirm it can connect.

Having checks that confirm you can connect to dependent services (databases, other apps etc) is a good thing. But the ELB health checks are made multiple times a second across all instances. They only care whether an app is up or not. So if, for example, you include querying your DB in  `/status` you're hitting your DB with multiple connections per second, multiplied by the number of server instances you have running.

Including reading a file from disk each time means we're adding an unnecessary load on a service that already has performance and resource usage issues.

We've already added a new `/health/info` endpoint to each repo and we do DB connection checks elsewhere. So, we can reduce the work of our `/status` endpoint across all the repos to the bare minimum; returning a static`{ "status": "alive" }` response.

- [x] Update [water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui) `/service-status` to use `/health/info` endpoints
- [x] water-abstraction-import
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-returns
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-ui

**Comment by Cruikshanks** [comment]
For reference, I spotted that the [water-abstraction-reporting](https://github.com/DEFRA/water-abstraction-reporting/blob/main/src/controllers.js#L15) and [water-abstraction-returns](https://github.com/DEFRA/water-abstraction-returns/blob/main/src/lib/connectors/status.js) were doing DB checks. They might be in others, I wasn't checking too closely.

**Comment by Jozzey** [comment]
<img src="https://media0.giphy.com/media/3o6ZsZbUukGiYMf2a4/giphy.gif"/>
