### ISSUE TITLE
Apply consistent GitHub labels across projects

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#7]
In our [Ways of working](https://github.com/DEFRA/water-abstraction-team/blob/main/ways_of_working.md#label-everything) we outline the need to label all PR's.

The list of labels we use is a mix of current GitHub defaults and our own. For some of the team, they are used across other services we maintain.

If we are going to start applying them we need to whizz through the various repos and ensure they are all using the same labels, and that they include our list (referenced again below)

|Name         |Description                                                     |
|-------------|----------------------------------------------------------------|
|bug          |Something isn't working                                         |
|dependencies |Pull requests that update a dependency file                     |
|documentation|Improvements or additions to documentation                      |
|enhancement  |New feature or request                                          |
|housekeeping |Refactoring, tidying up or other work which supports the project|
|security     |Pull requests that address a security vulnerability.            |

**Comment by jonathangoulding** [comment]
Mentioned on a PR for the documentation and added here. 

We can use actions to automatically label the PR's. We can go a step further with conventional commits as the commit message standard and use an action to label the PR's based on the commits. (Multiple labels if a doc is updated and bug fixed)

```
I would suggest this be automated:

Using conventional commits - https://github.com/action-runner/conventional-labeler

And this action for folder / file changes - https://github.com/actions/labeler (could be useful for the cypress test changes in the UI repo)

https://www.conventionalcommits.org/en/v1.0.0/
```

**Comment by Cruikshanks** [comment]
Done!

All repos have the same labels, descriptions and colours.
