### ISSUE TITLE
We might need to replace Objection.js!

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/water-abstraction-team#81]
When looking to find an example of how to do something in [Objection.js](https://github.com/Vincit/objection.js) I came across a reddit thread; [Well, s##t. Objection.js has been sunset, which ORM/querybuilder did you move to?](https://www.reddit.com/r/node/comments/zblmqf/well_shit_objectionjs_has_been_sunset_which/)

That led me to [The future of Objection.js](https://github.com/Vincit/objection.js/issues/2335)

> As you may have noticed, the development of Objection has been very slow this year. That's because I've been the only active long-term developer since I created this project and I just haven't worked on it lately.
> [...]
> I'm happy to transfer this project to someone else's care if that can somehow be arranged, but other than that, I won't be working on Objection anymore.
> [Sami Koskimäki](https://github.com/koskimas)

This was posted in November 2022. There is lots of chatter with a couple of folks stepping forward to keep the lights on (reviewing and approving minor PR's and pushing releases). But as yet no one has agreed to take over Objection.js permanently.

😱😭😩

We completely understand but it does leave us with a bit of an issue. Objection.js was going to be one of the cornerstones of a cleaner, easier-to-maintain WRLS service in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system).

We've _got_ to get supplementary billing and its associated functions done ASAP. **Objection.js** isn't dead so there is no immediate panic. But the team should start casting the net for alternatives (word of warning; it's grim out there ☹️) before we base any further functionality on it.

**Comment by tafelnl** [comment]
I would suggest taking a look at Prisma ORM

**Comment by Jozzey** [comment]
<img src="https://media4.giphy.com/media/OHsStjtsUJWjC/giphy.gif"/>

**Comment by marksark** [comment]
there have been updates to that discussion and while it's not as actively maintained as it used to be there are 2-3 superstars who stepped in and are trying to continue to work on things. There is a company that also keeps their own version of it forked and used and they are pushing some of their PRs to the community for updates so I think we're still good here for a while :)

**Comment by Cruikshanks** [comment]
> there have been updates to that discussion and while it's not as actively maintained as it used to be there are 2-3 superstars who stepped in and are trying to continue to work on things. There is a company that also keeps their own version of it forked and used and they are pushing some of their PRs to the community for updates so I think we're still good here for a while :)

Thank you for the update @marksark . Things definitely look more rosy for **Objection.js**, thank goodness, because we think it's ace!

Taking this off our issues list now 😁
