### ISSUE TITLE
Delete `CreateTransactionsService` / `CreateBillingTransactionService`

### ISSUE THREAD

**Issue by StuAA78** [DEFRA/water-abstraction-team#89]
We have a simple service `app/services/supplementary-billing/create-billing-transaction.service.js` which exists to create transactions. We haven't actually used it anywhere, preferring instead to create them directly using `BillingTransactionModel`. This, coupled with the fact that we don't have corresponding services for creating billing invoices and billing invoice licences, means we should probably delete it.

(Note that the ambiguous issue title is due to it being referred to as `CreateTransactionsService` within the service, and `CreateBillingTransactionService` within its unit tests.)

**Comment by Cruikshanks** [comment]
Done!
