### ISSUE TITLE
Replace ESLint with StandardJS

### ISSUE THREAD

**Issue by StuAA78** [DEFRA/water-abstraction-team#9]
[Defra's JavaScript standard](https://github.com/DEFRA/software-development-standards/blob/master/standards/javascript_standards.md) is to use [StandardJS](https://standardjs.com/) for linting. We currently use ESLint, configured to Semi-Standard (ie. StandardJS with semicolons). For consistency, we should change this to the regular Standard rules, and replace ESLint with StandardJS while we're at it.

- [x] water-abstraction-ui
- [x] water-abstraction-admin-ui
- [x] water-abstraction-service
- [x] water-abstraction-tactical-crm
- [x] water-abstraction-import
- [x] water-abstraction-tactical-idm
- [x] water-abstraction-returns
- [x] water-abstraction-permit-repository
- [x] water-abstraction-reporting
- [x] water-abstraction-helpers
- [x] hapi-pg-rest-api

**Comment by Cruikshanks** [comment]
![yes](https://user-images.githubusercontent.com/1789650/168174300-377c2281-9b2c-464d-a880-26c66f1ad805.gif)

TBH, you can drop the 'consider.' We are going to do this!

We'll just go one repo at a time and see what breaks. Also means we can deal with the issues we have with the ESlint dependencies (it feels like _a lot_ and most are creaking!)
